### ISSUE TITLE
contribution_report.py KeyError: 'data'

### ISSUE THREAD

**Issue by fujitatomoya** [fujitatomoya/github_activity#1]
```bash
Traceback (most recent call last):
  File "contribution_report.py", line 194, in <module>
    main()
  File "contribution_report.py", line 188, in main
    contributions = query_contributions(
  File "contribution_report.py", line 99, in query_contributions
    contributions += query_contribution(token, search_query)
  File "contribution_report.py", line 78, in query_contribution
    results = graphql_query(contribution_query, token)['data']
KeyError: 'data'
```

**Comment by fujitatomoya** [comment]
i think that `request.status_code == 200` returns with empty if the request data is long time ago like a year. in that case, we can get 200 but empty result and then generate `Key Error`. adding `try, except` statement to avoid the exception.

**Comment by fujitatomoya** [comment]
addressed in https://github.com/fujitatomoya/github_activity/commit/3cd3aadbc18a4879078bb831e57f6bd1edfa1d20
